### ISSUE TITLE
feature: Show todos only in current buffer

### ISSUE THREAD

**Issue by Tschimmy** [bezhermoso/todos-lualine.nvim#2]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I want, like I do with diagnostics, show the todos only of my current buffer. At work we have a big monorepo with a lot of ToDos that are out of my control. That makes showing all todos of my workspace a little bit misleading for me. I am much more interested in the current buffer and what I need to do there.

### Describe the solution you'd like

See only those Todos, Notes, etc. of my current buffer

### Describe alternatives you've considered

I can't see and still use it like it is now.

**Comment by bezhermoso** [comment]
Hi @Tschimmy this is currently beholden to what the underlying plugin I'm getting the data from offers, I'm gonna look into whether it can provide buffer-local data. If so it should be trivial to add.

**Comment by bezhermoso** [comment]
@Tschimmy I've added support for file-local todos data via this configuration:

```lua
local todos_component = require("todos-lualine").component({
  cwd = "%",
})
```

The only caveat is that it still does the search on the file on disk instead as searching the buffer (i.e. wouldn't count todos in unsaved changes), otherwise this should give you what you are asking for.
